spring:
  security:
    oauth2:
      client:
        registration: # ????? ??
          keycloak:
            authorization-grant-type: authorization_code # OAuth 2.0 ?? ?? ??
            client-id: oauth2-client-app # ??? ???? ??? ????? ???
            client-name: oauth2-client-app # ????? ??
            client-secret: tynl8eYUw4H1fJYxwLQ36XhFC1Ge1w1x # ??? ???? ??? ????? ????
            redirect-uri: http://localhost:8081/login/outh2/code/keycloak # ?????? ?? ?? ?? ? ?????? ????? ?? ??
            clientAuthenticationMethod: client_secret_post # ????? ???? ????
            scope: openid, email # ???? ?? ?? ??
      provider: #??? ??
        keycloak:
          authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth # OAuth 2.0 ?? ?? ?? ?? ???
          issuer-uri: http://localhost:8080/realms/oauth2 # ??? ??? ??
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs # OAuth 2.0 JwkSetUri ?? ???
          token-uri: http://localhost:8080/realms/outh2/protocol/openid-connect/token # OAuth 2.0 ?? ?? ???
          user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo # OAuth 2.0 UserInfo ?? ???
          user-name-attribute: preferred_username # OAuth 2.0 ????? ???? ????
